version: '3.8'


services:
  api:
    build: .
    container_name: teste-pratico-api
    ports:
      - '3000:3000'
    env_file:
      - .env
    depends_on:
      - postgres
  
  postgres:
    image: postgres:13
    container_name: teste-pratico-api-db
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
